### PR TITLE
Box Plot

### PR DESCRIPTION
**Pull request by rhodeskl**
Added box plots to better visualize the room data. The room data was displayed as vertical lines in the scatter plots since the room numbers can only be whole numbers. I also added a graph to show the total square footage of a house versus the price and a list of the number of zeros from each column that were excluded from the box plots.

### CODE REVIEW

**Comment by coffeechris** [comment]
Looks like you left the code block in `Let's Visualize The Relationship Each Feature Has With Price` commented out.

**Comment by coffeechris** [comment]
Can you drop the image renders from what you are trying to merge?

**Comment by jasonlewismedia** [comment]
I think this pull request may be against this forked repo in your space.  You may need to do a separate one targeting atomantic/ml_class:master

**Comment by coffeechris** [comment]
@jasonlewismedia - Yep that is the plan. Just working through the basics of forks and PRs

**Comment by coffeechris** [comment]
In section `Box Plots for Each Column`
* Can you add a blurb about why you are using box plots here and what specifically is being displayed. Not everyone will be familiar with the box plot and why they are useful.
* If you are not using the line `plt.close()` can you remove it?
* Currently you are applying the box plot to each column. That isn't what original motivated that visualization though. It was the shortcomings with the scatterplots for features that had a small and discrete range. For example: Kitchen AbvGr, Half Bath, Garage Cars, Full Bath, Fireplaces, Bsmt Half Bath, Bsmt Full Bath, Bedroom AbvGr.
  * You should be able to create a plot that displays several box plots for a given feature. Each plot would represent the average and standard deviations in sale price for a particular value. For example with Bedroom AbvGr, there should be at least 5 box plots for values 1 to 6.
* Can you update the figure dimensions so that we don't have to scroll to the output display?

**Comment by coffeechris** [comment]
In section `The Number of Zeros in Each Column`
* Can you talk about why zeros are problematic and why you are counting them here?

**Comment by coffeechris** [comment]
In section `Aggregate Graphs`
* Can you explain why you are looking at the aggregates and what value it is providing?

**Comment by coffeechris** [comment]
`The box plots exclude 0s from their graphs if some houses have a 0 in their data for the feature the box plots are representing to make the data they are representing more meaningful.`
Might be better if it is 
`The box plots exclude 0s from their graphs as some houses have 0s in their feature vector. That makes the resulting visualizations more meaningful.`

**Review by coffeechris — APPROVED** [review]
Just a language tweak. After you merge, submit a PR to @atomantic to get your fork merged in.

**Pull request merged**
